INSERT INTO herba_imatges ("idHerba", ruta_imatge, descripcio) VALUES
(199, 'imatges/galeria/acant/Acant_01.jpg', 'Imatge general'),
(199, 'imatges/galeria/acant/Acant_02.jpg', 'Imatge general'),
(199, 'imatges/galeria/acant/Acant_03.jpg', 'Imatge general'),
(199, 'imatges/galeria/acant/Acant_04.jpg', 'Imatge general'),
(199, 'imatges/galeria/acant/Acant_flor.jpg', 'Detall de la flor (_flor)'),
(199, 'imatges/galeria/acant/Acant_fruit.jpg', 'Detall del fruit (_fruit)'),
(199, 'imatges/galeria/acant/Acant_fulla.jpg', 'Detall de la fulla (_fulla)'),
(36, 'imatges/galeria/agrimoni/Agrimoni01.jpg', 'Imatge general'),
(36, 'imatges/galeria/agrimoni/Agrimoni02.jpg', 'Imatge general'),
(36, 'imatges/galeria/agrimoni/Agrimoni03.jpg', 'Imatge general'),
(36, 'imatges/galeria/agrimoni/Agrimoni04.jpg', 'Imatge general'),
(36, 'imatges/galeria/agrimoni/Agrimoni05.jpg', 'Imatge general'),
(36, 'imatges/galeria/agrimoni/Agrimoni06.jpg', 'Imatge general'),
(36, 'imatges/galeria/agrimoni/Agrimoni_flor.jpg', 'Detall de la flor (_flor)'),
(36, 'imatges/galeria/agrimoni/Agrimoni_fruit.jpg', 'Detall del fruit (_fruit)'),
(36, 'imatges/galeria/agrimoni/Agrimoni_fulla.jpg', 'Detall de la fulla (_fulla)'),
(30, 'imatges/galeria/alfabrega/Afàbrega01.jpg', 'Imatge general'),
(30, 'imatges/galeria/alfabrega/Afàbrega02.jpg', 'Imatge general'),
(30, 'imatges/galeria/alfabrega/Afàbrega03.jpg', 'Imatge general'),
(30, 'imatges/galeria/alfabrega/Afàbrega04.jpg', 'Imatge general'),
(30, 'imatges/galeria/alfabrega/Afàbrega_flor.jpg', 'Detall de la flor (_flor)'),
(30, 'imatges/galeria/alfabrega/Afàbrega_fruit.jpg', 'Detall del fruit (_fruit)'),
(30, 'imatges/galeria/alfabrega/Afàbrega_fulla.jpg', 'Detall de la fulla (_fulla)'),
(96, 'imatges/galeria/alfans/Alfans01.jpg', 'Imatge general'),
(96, 'imatges/galeria/alfans/Alfans02.jpg', 'Imatge general'),
(96, 'imatges/galeria/alfans/Alfans03.jpg', 'Imatge general'),
(96, 'imatges/galeria/alfans/Alfans_flor.jpg', 'Detall de la flor (_flor)'),
(96, 'imatges/galeria/alfans/Alfans_fruit.jpg', 'Detall del fruit (_fruit)'),
(96, 'imatges/galeria/alfans/Alfans_fulla.jpg', 'Detall de la fulla (_fulla)'),
(217, 'imatges/galeria/all/All01.jpg', 'Imatge general'),
(217, 'imatges/galeria/all/All02.jpg', 'Imatge general'),
(217, 'imatges/galeria/all/All_flor.jpg', 'Detall de la flor (_flor)'),
(217, 'imatges/galeria/all/All_fruit.jpg', 'Detall del fruit (_fruit)'),
(51, 'imatges/galeria/all_de_bruixa/AllDeBruixa01.jpg', 'Imatge general'),
(51, 'imatges/galeria/all_de_bruixa/AllDeBruixa02.jpg', 'Imatge general'),
(51, 'imatges/galeria/all_de_bruixa/AllDeBruixa03.jpg', 'Imatge general'),
(51, 'imatges/galeria/all_de_bruixa/AllDeBruixa04.jpg', 'Imatge general'),
(51, 'imatges/galeria/all_de_bruixa/AllDeBruixa05.jpg', 'Imatge general'),
(51, 'imatges/galeria/all_de_bruixa/AllDeBruixa_flor.jpg', 'Detall de la flor (_flor)'),
(51, 'imatges/galeria/all_de_bruixa/AllDeBruixa_fruit.jpg', 'Detall del fruit (_fruit)'),
(51, 'imatges/galeria/all_de_bruixa/AllDeBruixa_fulla.jpg', 'Detall de la fulla (_fulla)');